AtomicKitten:
  Framework:
    # All configuration options, used for build process.
    build:
      # Settings for generated output.
      target:
        # Folder to place generated output inside.
        outputFolder: '%FLOW_PATH_ROOT%Output/'
      # Settings for sources that will be parsed.
      source:
        # Related to framework parts. You can overwrite them to change the surrounding parts and functionality of AtomicKitten.
        framework:
          partials: '%FLOW_PATH_PACKAGES%Application/AtomicKitten.Framework/Resources/Private/Partials/'
          layouts: '%FLOW_PATH_PACKAGES%Application/AtomicKitten.Framework/Resources/Private/Layouts/'
          templates: '%FLOW_PATH_PACKAGES%Application/AtomicKitten.Framework/Resources/Private/Templates/'
        # Related to your AtomicKitten. Overwrite the paths to define where your templates can be found
        # That's the only parrt you HAVE to configure.
        atomicKitten:
          partials: '%FLOW_PATH_PACKAGES%Application/AtomicKitten.Example/Resources/Private/Partials/'
          layouts: '%FLOW_PATH_PACKAGES%Application/AtomicKitten.Example/Resources/Private/Layouts/'
          templates: '%FLOW_PATH_PACKAGES%Application/AtomicKitten.Example/Resources/Private/Templates/'
          # The format of provided templates. They have to use it as extension.
          format: 'html'
          folders:
            # Folders inside template folder, will be used to generate navigation in defined order.
            # Also, all files have to be in one of the folders.
            firstLevel:
              - Atoms
              - Molecules
              - Organisms
              - Templates
              - Pages
